from main.models import Equipment


equipmentStrings = """AIRLESS PAINT PUMP 8900 GAS 
AIRLESS PAINT PUMP 5500 GAS
AIRLESS PAINT PUMP 695
AIRLESS PAINT PUMP 595
AIRLESS PAINT PUMP 440
AIRLESS PAINT PUMP 395 (LATEX)
AIRLESS PAINT PUMP 395 (OIL BASE)
AIRLESS SPRAY GUN
AIRLESS SPRAY POLE
AIRLESS SPRAY TIP (SPECIFY SIZE)
AIRLESS HOUSING
AIRLESS SPRAY LINE 50' (3/8)
AIRLESS SPRAY LINE 50' (1/4)
AIRLESS SPRAY LINE ADAPTER
LINE STRIPER
PRO SHOT
POWER WASHER 
POWER WASHER FLOOR ATTACHMENT - BIG
POWER WASHER FLOOR ATTACHMENT - SMALL
POWER WASHER HOSE 50'
POWER WASHER HOSE 100'
POWER WASHER WAND/GUN
POWER WASHER TIPS
POWER WASHER ROTO TIP
POWER WASH EXTEND WAND
GARDEN HOSE 50"
GARDEN HOSE 100'
BACK PACK SPRAYER
FUEL CAN
2' ALUMINUM WORK PLATFORM
PERRY ROLLING SCAFFOLDING
ALUMINUM PLANK
FAN
GRINDER
CHOP SAW
TABLE SAW
7" CIRCULAR SAW
DRILL
PALM SANDER
GENERATOR
HEATER
LIGHT 
SANDING POLES
EXTENSION CORD
ROPE
PUSH BROOM
HOUSEHOLD BROOM
INTERIOR DROP CLOTH (RUNNER)
INTERIOR DROP CLOTH (AREA)
EXTERIOR DROP CLOTH (RUNNER)
EXTERIOR DROP CLOTH (AREA)
TARPS
RETRACTABLE (YO YO)
LANYARD
VACCUM
VACCUM HOSE
VACCUM ATTACHMENTS
LADDER PIVOTS
LADDER JACKS
LADDER STABILZERS
LADDER 4'
LADDER 8'
LADDER 16'
LADDER 20'
LADDER 24'
LADDER 28'
LADDER 32'
LADDER 40'
LADDER 60'
EXTENSION POLE 4 to 8
EXTENSION POLE 6 to 10
SAFETY HARNESS
DOUBLE PELICAN LANYARD
ROTO HAMMER
FACE  SHIELDS
PARAPIT HARNESS TIE DOWNS
MOP AND BUCKET
SAW HORSES
NAIL GUN
TRUCK HITCH
RAKE
TIRE CHALKS
NAIL GUN
DRYWALL KNIFE (SIZE)
DRYWALL PAN
DRYWALL TAPE
DRYWALL MUD"""


list_of_equipment = equipmentStrings.split('\n')

for i in list_of_equipment: 
    e = Equipment(name=i)
    e.save()
